### ISSUE TITLE
how to set and get window flags with therecipe qt bindings

### ISSUE THREAD

**Issue by omac777** [therecipe/qt#410]
There is qt example that sets the window flags at window creation:
http://doc.qt.io/qt-5/qtwidgets-widgets-shapedclock-example.html

I am now aware of QT WindowType which holds all flags making up the desired window behaviour and look:
https://doc.qt.io/archives/qtjambi-4.5.2_01/com/trolltech/qt/gui/QWidget.html#setWindowFlags(com.trolltech.qt.core.Qt.WindowType[])

within core/widgets.go, I found:
```
type Qt__WindowType int64
Qt__FramelessWindowHint
Qt__WindowSystemMenuHint
func (ptr *QGraphicsWidget) WindowFlags() core.Qt__WindowType
func (ptr *QGraphicsWidget) SetWindowFlags(wFlags core.Qt__WindowType)
```

I tried a few things with the internal/examples/gui/analogclock/analogclock.go, but none worked because it's the wrong type:
```
w.RasterWindow.init()
rwWinFlags := w.RasterWindow.Pointer().WindowFlags() //int64
rwWinFlags = rwWinFlags | core.Qt__FramelessWindowHint 
rwWinFlags = rwWinFlags | core.Qt__WindowSystemMenuHint
//w.RasterWindow.SetWindowFlags(rwWinFlags)
w.RasterWindow.Pointer().OverrideWindowFlags(rwWinFlags)
```

How do we dig through the type hierarchy to reach the correct WindowFlags(), SetWindowFlags(), OverrideWindowFlags() functions that should be part of QWidget, QWindow and RasterWindow from what I understand?

Thank you in advance.

**Comment by therecipe** [comment]
Hey

You are probably better of if you use the current documentation instead.
http://doc.qt.io/qt-5/qwindow.html and http://doc.qt.io/qt-5/qt.html#WindowType-enum

>How do we dig through the type hierarchy to reach the correct WindowFlags(), SetWindowFlags(), OverrideWindowFlags() functions that should be part of QWidget, QWindow and RasterWindow from what I understand?

Usually you don't have to upcast to get access to the correct functions.
As long as you don't "override" the `Flags` function in one of your derived classes, you can directly use it in any derived "class".

(But in case you still want to do it, you could use something like: `w.QWindow.Flags()`)

So this should work:

```go
rWinFlags := w.Flags() //uses (*gui.QWindow).Flags()
rWinFlags |= core.Qt__FramelessWindowHint
//or rWinFlags |= core.Qt__WindowSystemMenuHint
w.SetFlags(rWinFlags) //uses (*gui.QWindow).SetFlags()
```

Btw, sometimes it's necessary to convert enum types to primitives such as int64.
In those cases you can simply, write something like this:
`core.Qt__WindowType(0x00400000)` or `int64(core.Qt__MaximizeUsingFullscreenGeometryHint)`

**Comment by omac777** [comment]
yes thank you it worked.  I was still getting white rectangle surrounding the clock.  The following code fixes the region in the rasterwindow.go within analog clock.

```
func MyQMin(a, b int) int {
    if a < b {
        return a
    }
    return b
}

func (w *RasterWindow) renderNow() {
	if !w.IsExposed() {
		return
	}

	nSide := MyQMin( w.Width(), w.Height() )
	myRegionXPos := w.Width() / 2 - nSide / 2
	myRegionYPos := w.Height() / 2 - nSide / 2
	var rect = core.NewQRect4(myRegionXPos, myRegionYPos, w.Width(), w.Height())  
	qr3 := gui.NewQRegion3(rect, gui.QRegion__Ellipse) //set the ellipse within the qregion
	
	w.m_backingStore.BeginPaint(qr3)
	var device = w.m_backingStore.PaintDevice()
	var painter = gui.NewQPainter2(device)
	defer painter.DestroyQPainter()
	w.render(painter)
	w.m_backingStore.EndPaint()
	w.m_backingStore.Flush(gui.NewQRegion3(rect, gui.QRegion__Ellipse), w, core.NewQPoint())
}

```

**Comment by omac777** [comment]
Attempting to get a ShapedClock example derived from the AnalogClock example you have.
In similar fashion to Flags(), I can't seem to move the Main Window using w.Move() , w.QWindow.Move(), w.QWidget.Move():

```
func (w *RasterWindow) RasterWinMouseMoveEvent(ev *gui.QMouseEvent) {	
	fmt.Printf("RasterWinMouseMoveEvent: X():%d Y():%d\n", ev.X(), ev.Y())
        //w.QWidget_PTR().Move(Point1MinusPoint2(ev.GlobalPos(), w.m_dragPosition));
	w.QWindow_PTR().Move(Point1MinusPoint2(ev.GlobalPos(), w.m_dragPosition));
}

func (w *RasterWindow) RasterWinMousePressEvent(ev *gui.QMouseEvent) {
	fmt.Printf("RasterWinMousePressEvent: X():%d Y():%d\n", ev.X(), ev.Y())
	//w.m_dragPosition = ev.GlobalPos() - w.FrameGeometry().TopLeft()
	//core.QPoint
	//fmt.Printf("ev.GlobalPos():<<%v>>\n", ev.GlobalPos())
	//fmt.Printf("w.FrameGeometry():<<%v>>\n", w.FrameGeometry())
	//fmt.Printf("w.FrameGeometry().TopLeft():<<%v>>\n",w.FrameGeometry().TopLeft())
	qptGlobalPos := ev.GlobalPos()
	qptTopLeft := w.FrameGeometry().TopLeft()
	fmt.Printf("qptGlobalPos:<<%v>>\n", qptGlobalPos)
	fmt.Printf("qptTopLeft:<<%v>>\n", qptTopLeft)
	w.m_dragPosition = Point1MinusPoint2(qptGlobalPos, qptTopLeft)	
}

func (w *RasterWindow) RasterWinMouseReleaseEvent(ev *gui.QMouseEvent) {
	fmt.Printf("RasterWinMouseReleaseEvent X():%d Y():%d\n", ev.X(), ev.Y())
}

func Point1MinusPoint2(pt1 *core.QPoint, pt2 *core.QPoint) (*core.QPoint) {
	return core.NewQPoint2(pt1.X() - pt2.X(), pt1.Y() - pt2.Y())
}
```

**Comment by therecipe** [comment]
Ah, that looks nice.
You basically just got rid of the white rectangle or?

Because it seems like it has a black background on linux for me now, but also an translucent on macOS.

**Comment by omac777** [comment]
Yes, I removed the dirt on the remaining rectangle region:
1)set the mask
2)take away the rectangle paint within the render of the clock text.

**Comment by omac777** [comment]
Do you irc chat? why not /join #therecipeqt on freenode to create a channel there?

**Comment by therecipe** [comment]
Sorry, just saw your response now.
I always answer all open issues in batch and didn't expect a response that quickly.

And yeah, seems like the QWindow class has no "move" function.
So "setPosition" seems to be the only option.

About irc, there is already a slack channel: https://gophers.slack.com/messages/qt-binding/details
But even that one is not used that often.

**Comment by omac777** [comment]
I'm trying to add in the right click context menu as originally displayed within the QT ShapedClock example.  Everything attempted to cast or convert in order to get a popup menu from RasterWindow to either QWindow or Widget didn't succeed to provide the behaviour expected.  QMainWindow was never used in the shaped clock demo but it's the only type that has create popupmenu support at the moment within the golang bindings.

```
	ptrACW := w.Pointer()
	acwWidget := widgets.NewQWidgetFromPointer(ptrACW)
	
	menuAnalogClock := widgets.NewQMenu(acwWidget)
	menuActionExit := menuAnalogClock.AddAction("E&xit")
	menuActionExit.ConnectTriggered(func(checked bool) { w.Close() })
	menuActionExit.SetShortcut(gui.NewQKeySequence2("Ctrl+X", gui.QKeySequence__NativeText))
	
	acwWidget.SetContextMenuPolicy(core.Qt__ActionsContextMenu)
	acwWidget.SetToolTip("Drag the clock with the left mouse button.\nUse the right mouse button to open a context menu.")		

```

**Comment by omac777** [comment]
I just signed into mercuryfilmworks.slack.com and attempted to join your slack channel, but it doesn't seem to allow me.

**Comment by therecipe** [comment]
Yeah, casting from gui.QWindow to widgets.QWidget or so will not work.
For this to work you will probably need to use a QWidget in the first place.
But I'm not totally sure.

Could be that you need to get an invite first: https://invite.slack.golangbridge.org/
Yeah I'm no fan of Slack either, but it's the main channel for all Go communities.

**Comment by omac777** [comment]
The event type is not an update request so it never renders.  the window/widget is interpreted as not exposed so it never renders either.  It seems as there is a layer of windows/widgets going on and it's confusing as to which events the QWidget Main Window should capture and handle.

I added some debug print messages on the events.  It seems as though there are QEvent's destined for QWidget and others destined for QWindow. Yet in the scenario where the QWidget is the main window, it seems I can't capture some of those events i.e. updaterequest or updatelater.

How can I tell my QWidget main window to capture all events including its parent?
How can I convert incoming events from QWidget QEvent to QWindow QEvent and vice-versa?

```
package main

import (
	"os"
	"fmt"
	
	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

type AnalogClockQwdgt struct {
	widgets.QWidget

	_ func() `constructor:"init"`

	_ func() `slot:"renderLater"`
	_ func() `slot:"renderNow"`
	
	render func(painter *gui.QPainter)
	
	contextMenu *widgets.QMenu
	m_dragPosition *core.QPoint
	m_timerId int
}

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	var window = NewAnalogClockQwdgt(nil, core.Qt__FramelessWindowHint|core.Qt__WindowSystemMenuHint)
	window.Show()
	widgets.QApplication_Exec()
}

func (w *AnalogClockQwdgt) init() {
	w.Resize2(200, 200)
	w.m_timerId = w.StartTimer(1000, 0)
	w.ConnectTimerEvent(w.timerEvent)
	
	w.SetContextMenuPolicy(core.Qt__CustomContextMenu)
	w.ConnectCustomContextMenuRequested(w.customContextMenuRequested)
	w.SetToolTip("Drag the clock with the left mouse button.\nUse the right mouse button to open a context menu.")

	w.ConnectEvent(w.event)

	w.ConnectRenderLater(w.renderLater)
	w.ConnectRenderNow(w.renderNow)

	w.ConnectResizeEvent(w.resizeEvent)

	myQWindowFromQWidget := gui.QWindow_FromWinId(w.WinId())
	myQWindowFromQWidget.ConnectExposeEvent(w.exposeEvent)
	
	w.ConnectMouseMoveEvent(w.QWdgtMouseMoveEvent)
	w.ConnectMousePressEvent(w.QWdgtMousePressEvent)
	w.ConnectMouseReleaseEvent(w.QWdgtMouseReleaseEvent)

	w.render = w.renderFunc
}

func (w *AnalogClockQwdgt) timerEvent(event *core.QTimerEvent) {
	fmt.Printf("timerEvent()...\n")
	if event.TimerId() == w.m_timerId {
		fmt.Printf("timerEvent()...event.TimerId() == w.m_timerId\n")
		w.renderLater()
	}
}

func (w *AnalogClockQwdgt) customContextMenuRequested(p *core.QPoint) {
	fmt.Printf("customContextMenuRequested()...\n")
	if w.contextMenu == nil {
		fmt.Printf("customContextMenuRequested()...w.contextMenu == nil\n")
		w.contextMenu = widgets.NewQMenu(w)
		menuActionExit := w.contextMenu.AddAction("E&xit")
		menuActionExit.SetShortcut(gui.NewQKeySequence2("Ctrl+X", gui.QKeySequence__NativeText))
		menuActionExit.ConnectTriggered(func(checked bool) { w.Close() })
	}

	w.contextMenu.Exec2(w.MapToGlobal(p), nil)
}

func (w *AnalogClockQwdgt) renderFunc(p *gui.QPainter) {
	fmt.Printf("renderFunc()...\n")

	var hourHand = gui.NewQPolygon3([]*core.QPoint{
		core.NewQPoint2(7, 8),
		core.NewQPoint2(-7, 8),
		core.NewQPoint2(0, -40),
	})

	var minuteHand = gui.NewQPolygon4([]*core.QPoint{
		core.NewQPoint2(7, 8),
		core.NewQPoint2(-7, 8),
		core.NewQPoint2(0, -70),
	})

	var hourColor = gui.NewQColor3(127, 0, 127, 255)
	var minuteColor = gui.NewQColor3(0, 127, 127, 191)

	p.SetRenderHint(gui.QPainter__Antialiasing, true)

	p.Translate3(float64(w.Width())/2, float64(w.Height())/2)

	var side = func(a, b int) int {
		if a <= b {
			return a
		}
		return b
	}(w.Width(), w.Height())
	p.Scale(float64(side)/200.0, float64(side)/200.0)

	p.SetPen3(core.Qt__NoPen)
	p.SetBrush(gui.NewQBrush3(hourColor, 1))

	var time = core.QTime_CurrentTime()

	p.Save()
	p.Rotate(float64(30.0 * (time.Hour() + time.Minute()/60.0)))
	p.DrawConvexPolygon4(hourHand)
	p.Restore()

	p.SetPen2(hourColor)

	for i := 0; i < 12; i++ {
		p.DrawLine3(88, 0, 96, 0)
		p.Rotate(30.0)
	}

	p.SetPen3(core.Qt__NoPen)
	p.SetBrush(gui.NewQBrush3(minuteColor, 1))

	p.Save()
	p.Rotate(float64(6.0 * (time.Minute() + time.Second()/60.0)))
	p.DrawConvexPolygon4(minuteHand)
	p.Restore()

	p.SetPen2(minuteColor)

	for j := 0; j < 60; j++ {
		if (j % 5) != 0 {
			p.DrawLine3(92, 0, 96, 0)
		}
		p.Rotate(6.0)
	}
}

func (w *AnalogClockQwdgt) QWdgtMouseMoveEvent(ev *gui.QMouseEvent) {	
	fmt.Printf("QWdgtMouseMoveEvent()...\n")
	nMouseState := ev.MouseState()
	bLeftButtonPressed :=  bool(nMouseState == core.Qt__LeftButton)
	if(bLeftButtonPressed) {
		qptMoveHere := Point1MinusPoint2(ev.GlobalPos(), w.m_dragPosition)
		//w.SetPosition(qptMoveHere)
		w.Move(qptMoveHere)
	}	
}

func (w *AnalogClockQwdgt) QWdgtMousePressEvent(ev *gui.QMouseEvent) {
	fmt.Printf("QWdgtMousePressEvent()...\n")
	nMouseState := ev.MouseState()
	bLeftButtonPressed :=  bool(nMouseState == core.Qt__LeftButton)
	if(bLeftButtonPressed) {
		qptGlobalPos := ev.GlobalPos()
		qptTopLeft := w.FrameGeometry().TopLeft()
		w.m_dragPosition = Point1MinusPoint2(qptGlobalPos, qptTopLeft)	
	}
}

func (w *AnalogClockQwdgt) QWdgtMouseReleaseEvent(ev *gui.QMouseEvent) {
	fmt.Printf("QWdgtMouseReleaseEvent()...\n")
}

func Point1MinusPoint2(pt1 *core.QPoint, pt2 *core.QPoint) (*core.QPoint) {
	return core.NewQPoint2(pt1.X() - pt2.X(), pt1.Y() - pt2.Y())
}

func (w *AnalogClockQwdgt) renderNow() {
	fmt.Printf("renderNow()...\n")
	myQWindowFromQWidget := gui.QWindow_FromWinId(w.WinId())
	if !myQWindowFromQWidget.IsExposed() {
		fmt.Printf("renderNow()...IS NOT EXPOSED!!! NOT RENDERING!!!\n")
		return
	}

	nSide := MyQMin( w.Width(), w.Height() )
	myRegionXPos := w.Width() / 2 - nSide / 2
	myRegionYPos := w.Height() / 2 - nSide / 2
	var rect = core.NewQRect4(myRegionXPos, myRegionYPos, w.Width(), w.Height())  
	qr3 := gui.NewQRegion3(rect, gui.QRegion__Ellipse) //set the ellipse within the qregion
	
	w.BackingStore().BeginPaint(qr3)
	var device = w.BackingStore().PaintDevice()
	var painter = gui.NewQPainter2(device)
	defer painter.DestroyQPainter()
	w.render(painter)
	w.BackingStore().EndPaint()
	w.BackingStore().Flush(gui.NewQRegion3(rect, gui.QRegion__Ellipse), myQWindowFromQWidget, core.NewQPoint())	
}

func (w *AnalogClockQwdgt) renderLater() {
	fmt.Printf("renderLater()...\n")
	//myQWindowFromQWidget := gui.QWindow_FromWinId(w.EffectiveWinId())
	myQWindowFromQWidget := gui.QWindow_FromWinId(w.WinId())
	//myQWindowFromQWidget.RequestUpdateLater()
	//myQWindowFromQWidget.RequestUpdate()
	myQWindowFromQWidget.RequestUpdateDefault()
}

func MyQMin(a, b int) int {
    if a < b {
        return a
    }
    return b
}

func (w *AnalogClockQwdgt) event(ev *core.QEvent) bool {
	fmt.Printf("event()...ev.Type():<<%v>>\n",ev.Type())

	if (ev.Type() == core.QEvent__UpdateRequest) {
		fmt.Printf("event()...ev.Type() == core.QEvent__UpdateRequest\n")
		w.RenderNow()
		return true
	}

	if (ev.Type() == core.QEvent__UpdateLater) {
		fmt.Printf("event()...ev.Type() == core.QEvent__UpdateLater\n")
		w.RenderLater()
		return true
	}
	
	fmt.Printf("not an update request. ignored...\n")
	return w.EventDefault(ev)
}

func (w *AnalogClockQwdgt) resizeEvent(ev *gui.QResizeEvent) {
	fmt.Printf("resizeEvent()...\n")
        nSide := MyQMin( w.Width(), w.Height() )
        myRegionXPos := w.Width() / 2 - nSide / 2
        myRegionYPos := w.Height() / 2 - nSide / 2
        var rect = core.NewQRect4(myRegionXPos, myRegionYPos, w.Width(), w.Height())
        qr3 := gui.NewQRegion3(rect, gui.QRegion__Ellipse) //set the ellipse within the qregion
        w.SetMask2(qr3)

	w.BackingStore().Resize(ev.Size())
	
	myQWindowFromQWidget := gui.QWindow_FromWinId(w.WinId())
        if myQWindowFromQWidget.IsExposed() {
		fmt.Printf("resizeEvent()...myQWindowFromQWidget.IsExposed()\n")
                w.RenderNow()
        }
}

func (w *AnalogClockQwdgt) exposeEvent(ev *gui.QExposeEvent) {
	fmt.Printf("exposeEvent()...\n")
	myQWindowFromQWidget := gui.QWindow_FromWinId(w.WinId())
 	if myQWindowFromQWidget.IsExposed() {
		fmt.Printf("exposeEvent()...myQWindowFromQWidget.IsExposed()\n")
 		w.RenderNow()
 	}
}

```

**Comment by omac777** [comment]
Thank you again.  It helped a great deal.  I tweaked it to add an arcTo and discovered the paint context was rotated at the wrong angle.  It took me a while to determine that I need to wrap my painting tasks with p.Save() and p.Restore() in order to previous tasks' rotates not to effect the current tasks drawing operations.

```
package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

type AnalogClockQwdgt struct {
	widgets.QWidget

	_ func() `constructor:"init"`

	_ func() `slot:"renderLater"`
	_ func() `slot:"renderNow"`

	render func(painter *gui.QPainter)

	contextMenu    *widgets.QMenu
	m_dragPosition *core.QPoint
	m_timerId      int
}

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	var window = NewAnalogClockQwdgt(nil, core.Qt__FramelessWindowHint|core.Qt__WindowSystemMenuHint)
	window.Show()
	widgets.QApplication_Exec()
}

func (w *AnalogClockQwdgt) init() {
	w.Resize2(200, 200)
	w.m_timerId = w.StartTimer(1000, 0)
	w.ConnectTimerEvent(w.timerEvent)

	w.SetContextMenuPolicy(core.Qt__CustomContextMenu)
	w.ConnectCustomContextMenuRequested(w.customContextMenuRequested)
	w.SetToolTip("Drag the clock with the left mouse button.\nUse the right mouse button to open a context menu.")

	w.ConnectRenderLater(w.renderLater)
	w.ConnectPaintEvent(w.renderNow)
	w.ConnectResizeEvent(w.resizeEvent)

	w.ConnectMouseMoveEvent(w.QWdgtMouseMoveEvent)
	w.ConnectMousePressEvent(w.QWdgtMousePressEvent)
	w.ConnectMouseReleaseEvent(w.QWdgtMouseReleaseEvent)

	w.render = w.renderFunc
}

func (w *AnalogClockQwdgt) timerEvent(event *core.QTimerEvent) {
	fmt.Printf("timerEvent()...\n")
	if event.TimerId() == w.m_timerId {
		fmt.Printf("timerEvent()...event.TimerId() == w.m_timerId\n")
		w.renderLater()
	}
}

func (w *AnalogClockQwdgt) customContextMenuRequested(p *core.QPoint) {
	fmt.Printf("customContextMenuRequested()...\n")
	if w.contextMenu == nil {
		fmt.Printf("customContextMenuRequested()...w.contextMenu == nil\n")
		w.contextMenu = widgets.NewQMenu(w)
		menuActionExit := w.contextMenu.AddAction("E&xit")
		menuActionExit.SetShortcut(gui.NewQKeySequence2("Ctrl+X", gui.QKeySequence__NativeText))
		menuActionExit.ConnectTriggered(func(checked bool) { w.Close() })
	}

	w.contextMenu.Exec2(w.MapToGlobal(p), nil)
}

func (w *AnalogClockQwdgt) renderFunc(p *gui.QPainter) {
	fmt.Printf("renderFunc()...\n")
	var hourHand = gui.NewQPolygon3([]*core.QPoint{
		core.NewQPoint2(7, 8),
		core.NewQPoint2(-7, 8),
		core.NewQPoint2(0, -40),
	})

	var minuteHand = gui.NewQPolygon4([]*core.QPoint{
		core.NewQPoint2(7, 8),
		core.NewQPoint2(-7, 8),
		core.NewQPoint2(0, -70),
	})

	var hourColor = gui.NewQColor3(127, 0, 127, 255) //opaque 255  ...transparent 0
	var minuteColor = gui.NewQColor3(0, 127, 127, 191) //a bit of transparency
	var arcColor = gui.NewQColor3(255, 0, 0, 191) //transparent red

	p.SetRenderHint(gui.QPainter__Antialiasing, true)
	p.SetPen3(core.Qt__NoPen)
	p.SetBrush(gui.NewQBrush3(hourColor, 1))

	
	firstTranslateX := float64(w.Width())/2
	firstTranslateY := float64(w.Height())/2
	fmt.Printf("firstTranslateX:<<%v>>\n",firstTranslateX)
	fmt.Printf("firstTranslateY:<<%v>>\n",firstTranslateY)

	p.Translate3(firstTranslateX, firstTranslateY)

	nSide := MyQMin(w.Width(), w.Height())
	fmt.Printf("nSide:<<%v>>\n", nSide)

	fFirstScaleX := float64(nSide)/200.0
	fFirstScaleY := float64(nSide)/200.0
	fmt.Printf("fFirstScaleX:<<%v>>\n",fFirstScaleX)
	fmt.Printf("fFirstScaleY:<<%v>>\n",fFirstScaleY)
	
	p.Scale(fFirstScaleX, fFirstScaleY)


	var tTimeNow = core.QTime_CurrentTime()

	p.Save() //push 1
	myHourNow := tTimeNow.Hour()
	myMinuteNow := tTimeNow.Minute()
	fmt.Printf("myHourNow:<<%v>>\n", myHourNow)
	fmt.Printf("myMinuteNow:<<%v>>\n", myMinuteNow)
	myFirstRotate := float64(30.0 * (myHourNow + myMinuteNow/60.0))
	fmt.Printf("myFirstRotate for the hour hand:<<%v>>\n",myFirstRotate)
	p.Rotate(myFirstRotate)
	p.DrawConvexPolygon4(hourHand)
	p.Restore() //pop 1

	p.Save() //push 1
	p.SetPen2(hourColor)
	fmt.Printf("setting hour ticks...\n")
	for i := 0; i < 12; i++ {
		p.DrawLine3(88, 0, 96, 0)
		mySecondRotate := 30.0
		fmt.Printf("mySecondRotate for hour ticks:<<%v>>\n", mySecondRotate)
		p.Rotate(mySecondRotate)
	}

	p.SetPen3(core.Qt__NoPen)
	p.SetBrush(gui.NewQBrush3(minuteColor, 1))
	p.Restore() //pop 1


	
	p.Save() //push 1
	myThirdRotate := float64(6.0 * (tTimeNow.Minute() + tTimeNow.Second()/60.0))
	fmt.Printf("myThirdRotate for the minute hand:<<%v>>\n", myThirdRotate)
	p.Rotate(myThirdRotate)
	p.DrawConvexPolygon4(minuteHand)
	p.Restore() //pop 1

	

	p.Save() //push 1
	p.SetPen2(minuteColor)
	fmt.Printf("setting minute ticks...\n")
	for j := 0; j < 60; j++ {
		if (j % 5) != 0 {
			p.DrawLine3(92, 0, 96, 0)
		}
		
		myFourthRotate := 6.0
		fmt.Printf("myFourthRotate for the minute ticks:<<%v>>\n", myFourthRotate)
		p.Rotate(myFourthRotate)
		
	}
	p.Restore() //pop 1
	

	p.SetPen2(arcColor)
	p.SetBrush(gui.NewQBrush3(arcColor, 1))

	//x,y is the centerpoint
	//r is the radius
	//rect is the bounding rectangle
	//myRegionXPos, myRegionYPos, w.Width(), w.Height()
	fmt.Printf("w.Width():<<%v>>\n", w.Width())
	fmt.Printf("w.Height():<<%v>>\n", w.Height())	
	//nSide := MyQMin(w.Width(), w.Height())
	myRegionXPos := float64(w.Width())/2.0 - float64(nSide)/2.0
	myRegionYPos := float64(w.Height())/2.0 - float64(nSide)/2.0
	theRadius := float64(w.Width())/2.0
	//theCenterX := float64(w.Width())/2.0
	//theCenterY := float64(w.Height())/2.0
	xPosForArc := myRegionXPos - theRadius
	yPosForArc := myRegionYPos - theRadius
	rectBoundingForArc := core.NewQRectF4(xPosForArc, yPosForArc, 2*theRadius, 2*theRadius)
	// QPainterPath piePath;
	// NewQPainterPath() *QPainterPath
	myPiePainterPath := gui.NewQPainterPath()
	//We are already translated with p so we don't need to move/translate any further.
	//myPiePainterPath.MoveTo2(firstTranslateX, firstTranslateY)
	//myPiePainterPath.MoveTo2(theCenterX, theCenterY) //should move to the center
	//p.Translate3(0.0, 0.0)

	// piePath.arcTo(20.0, 30.0, 60.0, 40.0, 60.0, 240.0);
	// (ptr *QPainterPath) ArcTo(qrectF, startAngle float64, sweepLengthAngle float64)
	myPiePainterPath.ArcTo(rectBoundingForArc.QRectF_PTR(), 40.0, 90.0)
	myPiePainterPath.CloseSubpath()
	p.DrawPath(myPiePainterPath)	
}

func (w *AnalogClockQwdgt) QWdgtMouseMoveEvent(ev *gui.QMouseEvent) {
	fmt.Printf("QWdgtMouseMoveEvent()...\n")
	nMouseState := ev.MouseState()
	bLeftButtonPressed := bool(nMouseState == core.Qt__LeftButton)
	if bLeftButtonPressed {
		qptMoveHere := Point1MinusPoint2(ev.GlobalPos(), w.m_dragPosition)
		//w.SetPosition(qptMoveHere)
		w.Move(qptMoveHere)
	}
}

func (w *AnalogClockQwdgt) QWdgtMousePressEvent(ev *gui.QMouseEvent) {
	fmt.Printf("QWdgtMousePressEvent()...\n")
	nMouseState := ev.MouseState()
	bLeftButtonPressed := bool(nMouseState == core.Qt__LeftButton)
	if bLeftButtonPressed {
		qptGlobalPos := ev.GlobalPos()
		qptTopLeft := w.FrameGeometry().TopLeft()
		w.m_dragPosition = Point1MinusPoint2(qptGlobalPos, qptTopLeft)
	}
}

func (w *AnalogClockQwdgt) QWdgtMouseReleaseEvent(ev *gui.QMouseEvent) {
	fmt.Printf("QWdgtMouseReleaseEvent()...\n")
}

func Point1MinusPoint2(pt1 *core.QPoint, pt2 *core.QPoint) *core.QPoint {
	return core.NewQPoint2(pt1.X()-pt2.X(), pt1.Y()-pt2.Y())
}

func (w *AnalogClockQwdgt) renderNow(ev *gui.QPaintEvent) {
	fmt.Printf("renderNow()...\n")

	nSide := MyQMin(w.Width(), w.Height())
	myRegionXPos := w.Width()/2 - nSide/2
	myRegionYPos := w.Height()/2 - nSide/2
	var rect = core.NewQRect4(myRegionXPos, myRegionYPos, w.Width(), w.Height())
	qr3 := gui.NewQRegion3(rect, gui.QRegion__Ellipse) //set the ellipse within the qregion

	w.BackingStore().BeginPaint(qr3)
	var device = w.BackingStore().PaintDevice()
	var painter = gui.NewQPainter2(device)
	defer painter.DestroyQPainter()
	w.render(painter)
	w.BackingStore().EndPaint()
	w.BackingStore().Flush(gui.NewQRegion3(rect, gui.QRegion__Ellipse), nil, core.NewQPoint())
}

func (w *AnalogClockQwdgt) resizeEvent(ev *gui.QResizeEvent) {
	fmt.Printf("resizeEvent()...\n")
	nSide := MyQMin(w.Width(), w.Height())
	myRegionXPos := w.Width()/2 - nSide/2
	myRegionYPos := w.Height()/2 - nSide/2
	var rect = core.NewQRect4(myRegionXPos, myRegionYPos, w.Width(), w.Height())
	qr3 := gui.NewQRegion3(rect, gui.QRegion__Ellipse) //set the ellipse within the qregion
	w.SetMask2(qr3)

	w.BackingStore().Resize(ev.Size())

	w.RenderLater()
}

func (w *AnalogClockQwdgt) renderLater() {
	fmt.Printf("renderLater()...\n")
	w.Update()
}

func MyQMin(a, b int) int {
	if a < b {
		return a
	}
	return b
}

```

**Comment by therecipe** [comment]
Awesome, I just tested it on Linux and macOS :)
Can I use it as an example?

**Comment by omac777** [comment]
Of course! Thanks for the compliment.

**Comment by erfanio** [comment]
I'm trying to get this code (from examples) to work but I can't get it to compile:
```
./main.go:31:15: undefined: NewAnalogClockQwdgt     
./main.go:45:3: w.ConnectRenderLater undefined (type *AnalogClockQwdgt has no field or method ConnectRenderLater)
./main.go:257:3: w.RenderLater undefined (type *AnalogClockQwdgt has no field or method RenderLater, but does have renderLater)
```

The use of struct tags here is not clear to me. Also I don't know where `NewAnalogClockQwdgt` is supposed to be defined.

**Comment by omac777** [comment]
On 10/08/2017 05:27 AM, Erfan wrote:
> I'm trying to get this code (from examples) to work but I can't get it to compile:
> ```
> ./main.go:31:15: undefined: NewAnalogClockQwdgt     
> ./main.go:45:3: w.ConnectRenderLater undefined (type *AnalogClockQwdgt has no field or method ConnectRenderLater)
> ./main.go:257:3: w.RenderLater undefined (type *AnalogClockQwdgt has no field or method RenderLater, but does have renderLater)
> ```
> 
> The use of struct tags here is not clear to me. Also I don't know where `NewAnalogClockQwdgt` is supposed to be defined.
> 

That code can compile with go1.8rc1 to go1.9.1 from my experience.
The more recent versions of go have a feature the gives you
New[WHATEVERTYPEYOUDEFINE] and it will return an instance of it.  That's
why you can't find 'NewAnalogClockQwdgt' in main.go.  There are other
ways of instantiating and you are more than welcome to change the code
to make it compile for you.  Your qt version is not recent enough, it
will not compile because it relies on a newer feature of qt5.9+ to make
it happen.

ConnectRenderLater and RenderLater are both defined in the main.go.
