### ISSUE TITLE
Problems with github actions

### ISSUE THREAD

**Issue by akiyosi** [therecipe/qt#1124]
Hi :)
I'm currently working on a Github Actions script for my project.
And now I have two problems.
I would appreciate any advice you can give me.

### Problem 1

The script will work with Qt 5.13, but if I use Qt 5.12, I will get the following error.

```
...
ime="2020-06-02T16:23:37Z" level=info msg="generating full qt/sailfish"
time="2020-06-02T16:23:37Z" level=info msg="generating full qt/webview"
time="2020-06-02T16:23:37Z" level=info msg="generating full qt/remoteobjects"
time="2020-06-02T16:23:38Z" level=warning msg=parser.LoadModule error=EOF module=Qml
time="2020-06-02T16:23:38Z" level=warning msg=parser.LoadModule error=EOF module=Core
time="2020-06-02T16:23:38Z" level=info msg="running: 'qtsetup install linux' [docker=false] [vagrant=false]"
time="2020-06-02T16:23:38Z" level=info msg="installing full qt/core"
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
##[error]src/github.com/therecipe/qt/core/core.go:15:42: undefined: NewQByteArrayFromPointer

time="2020-06-02T16:23:40Z" level=error msg="failed to install 'core'; aborting setup"
```

From past issues, it seems that this problem may occur when GO111MODULE=on, but the script exports GO111MODULE=off.
I've tried a lot of things and it doesn't work. For example, I checkeout previous commits in `therecie/qt` and re-built and repositioned the related commands, but it does not work.

### Problem 2
When Qt5.13 is specified in the script, the CI works fine and the package is generated successfully, but on macOS, the `@rpath` to refer to the included QtWebEngineProcess dynamic library seems to be incorrect.

---
Here's a script I'm working on for your reference

The script with use Qt5.13
https://github.com/akiyosi/goneovim/blob/master/.github/workflows/go.yml

The script with use Qt5.12
https://github.com/akiyosi/goneovim/blob/qt-512/.github/workflows/go.yml

**Comment by monkeyWie** [comment]
You can see my github action, https://github.com/monkeyWie/github-actions-demo/blob/master/.github/workflows/qt.yml

**Comment by akiyosi** [comment]
Hi,
I tried again with the latest binding and get the same problem.

Is there any workaround that I can do at hand?

**Comment by therecipe** [comment]
Hey

Sorry for the wait.
I looked into this and attached the updated scripts [go_yml.zip](https://github.com/therecipe/qt/files/5171737/go_yml.zip)

Also btw, you can also use QT_VERSION=5.12.8 with QT_API=5.13.0 or the other way around use QT_VERSION=5.13.2 with QT_API=5.12.0, so that you don't need to maintain two branches / or edit the source to work with both 5.12 and 5.13

About the second problem, I pushed some change https://github.com/therecipe/qt/commit/6d2596ed6fe1669abb4d06ec14341bdf39157cb0#diff-16e44658fb89a392fbb49ad74fdc4570, which should not affect the behavior of deployed builds. But it might fix problems on dev machines.

I also tested the latest build from the release page and it seems to work fine for me
<img width="868" alt="screen" src="https://user-images.githubusercontent.com/9833226/92182393-e75fe200-ee4b-11ea-9171-3d8ca01d8b90.png">

**Comment by akiyosi** [comment]
Hi :D 
Thanks for the reply.

I tried the script you gave me but it didn't build well.
There are two problems, one with the binding generation on MacOS and another with the build failure on Windows.
https://github.com/akiyosi/goneovim/actions/runs/239430873

I used the QT_API control before, but it didn't work well for my project. There may be something in my project that prevents the QT_API from controlling it. Currently, I haven't been able to fully isolate where the inhibitors are.

>  also tested the latest build from the release page and it seems to work fine for me

The latest binaries in the release of my project are built manually on my machine. 
If the build with the Actions works out, I'm hoping to use it for the release build as well.

**Comment by akiyosi** [comment]
Hi,
I've looked for th recent of the problem, it was a combination entanglement of trivial problem.
That is;
 - Specify `QT_DIR`
 - Add Qt module: `modules: 'qtcharts qtdatavis3d qtpurchasing qtvirtualkeyboard qtwebengine qtnetworkauth qtwebglplugin qtscript'
`
 - On Windows, specify `arch:'win64_msvc2017_64'` in the installation.

WI fixed these issues and were finally able to successfully build for all platforms.
I am deeply grateful for your great work and support.😀
