### ISSUE TITLE
undefined: qt.HexDecodeToString

### ISSUE THREAD

**Issue by pekim** [therecipe/qt#103]
My application, and the examples in the `internal/examples`, fail to build with `undefined: qt.HexDecodeToString`,

As far as I can tell (from checking out various commits and running `qtdeploy`), this was introduced by https://github.com/therecipe/qt/commit/2ac66d23735c7cb2b0b1270941e41913c0702cd0.

`func HexDecodeToString(in string) string` was removed from `qt.go` by that commit. However there are lots of calls to the function.

**Comment by therecipe** [comment]
Hey

Yes, I removed the function because it was only used to convert QByteArray to a primitive Go string.
And now QByteArray is a normal class and can work without that help function.
It had to do with this issue: https://github.com/therecipe/qt/issues/98#issuecomment-259492408

I hope that doesn't break much of your code.
To fix this, you can most times simply use `*.ConstData()` if you received a QByteArray to get the string.

Or if the functions expected a QByteArray parameter, you need to create a QByteArray with NewQByteArray2(data, len(data)).

Another function that will probably be removed in the future is `qt.Identifier`, and I may rename `GetSignal`, `ConnectSignal`, ... into `GetCallback`, `ConnectCallback`.
But I will wrap them up previously and let them print a deprecated warning.

**Comment by pekim** [comment]
I was seeing problems with this function missing when `qtsetup` built the examples. I wonder if I had some old object files lying around that were being found. I'll try building again from master.

**Comment by pekim** [comment]
No, still failing. If I run `qtsetup` from `master` it fails.
http://pastebin.com/eX2UzUDu

If I run `qtsetup` from `26cfccc` then it builds successfully.

**Comment by therecipe** [comment]
Could you try it again with https://github.com/therecipe/qt/commit/71c4fb9fdc45f89910280ba5401d15f4191fc045?

**Comment by pekim** [comment]
I think that I screwed up somewhere along the line. My `qtsetup` was an old version. I've `go get ...`ed again, and it's all fine now.

Sorry for the noise.

(I'm using https://github.com/therecipe/qt/commit/71c4fb9fdc45f89910280ba5401d15f4191fc045, but I'm not sure that's what sorted it.)

**Comment by therecipe** [comment]
No problem, it was my fault ;)
I didn't tried to `go get` or pull a new version to test if it would work, if there were old "generated" files present. But I had the same problem, after I pulled the repo.
