### ISSUE TITLE
Error no -lc++

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#765]
Hi,

I'm trying to build my app to android using latest binding, Qt 5.11.2, ndk 18b, and latest android sdk ... but got following error:
```
/Users/arknable/Development/Stackninja/Tools/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc++
core-minimal.cpp:153: error: undefined reference to '__dynamic_cast'
core-minimal.cpp:155: error: undefined reference to '__dynamic_cast'
core-minimal.cpp:157: error: undefined reference to '__dynamic_cast'
core-minimal.cpp:159: error: undefined reference to '__dynamic_cast'
/var/folders/85/kyr54pgx1jq2rwt0_bc9csyw0000gn/T/go-build576435461/b261/_x004.o(.ARM.extab+0x0): error: undefined reference to '__gxx_personality_v0'
/var/folders/85/kyr54pgx1jq2rwt0_bc9csyw0000gn/T/go-build576435461/b261/_x004.o(.ARM.extab+0x164): error: undefined reference to '__gxx_personality_v0'
/var/folders/85/kyr54pgx1jq2rwt0_bc9csyw0000gn/T/go-build576435461/b261/_x004.o(.ARM.extab+0x180): error: undefined reference to '__gxx_personality_v0'
/var/folders/85/kyr54pgx1jq2rwt0_bc9csyw0000gn/T/go-build576435461/b261/_x004.o(.ARM.extab+0x1a4): error: undefined reference to '__gxx_personality_v0'
/Applications/Qt/5.11.2/android_armv7/include/QtCore/qlist.h:816: error: undefined reference to '__cxa_begin_catch'
/Applications/Qt/5.11.2/android_armv7/include/QtCore/qlist.h:818: error: undefined reference to '__cxa_rethrow'
/Applications/Qt/5.11.2/android_armv7/include/QtCore/qlist.h:819: error: undefined reference to '__cxa_end_catch'
/Applications/Qt/5.11.2/android_armv7/include/QtCore/qlist.h:594: error: undefined reference to '__cxa_begin_catch'
/Applications/Qt/5.11.2/android_armv7/include/QtCore/qlist.h:596: error: undefined reference to '__cxa_rethrow'
/Applications/Qt/5.11.2/android_armv7/include/QtCore/qlist.h:597: error: undefined reference to '__cxa_end_catch'
/Applications/Qt/5.11.2/android_armv7/include/QtCore/qlist.h:585: error: undefined reference to '__cxa_begin_catch'
/Applications/Qt/5.11.2/android_armv7/include/QtCore/qlist.h:587: error: undefined reference to '__cxa_rethrow'
/Applications/Qt/5.11.2/android_armv7/include/QtCore/qlist.h:588: error: undefined reference to '__cxa_end_catch'
/Applications/Qt/5.11.2/android_armv7/include/QtCore/qlist.h:603: error: undefined reference to '__cxa_begin_catch'
/Applications/Qt/5.11.2/android_armv7/include/QtCore/qlist.h:605: error: undefined reference to '__cxa_rethrow'
/Applications/Qt/5.11.2/android_armv7/include/QtCore/qlist.h:606: error: undefined reference to '__cxa_end_catch'
/var/folders/85/kyr54pgx1jq2rwt0_bc9csyw0000gn/T/go-build576435461/b261/_x004.o:core-minimal.cpp:function __clang_call_terminate: error: undefined reference to 'std::terminate()'
/var/folders/85/kyr54pgx1jq2rwt0_bc9csyw0000gn/T/go-build576435461/b261/_x004.o:core-minimal.cpp:typeinfo for MyQAbstractItemModel: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
/Users/arknable/Development/Stackninja/Tools/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/var/folders/85/kyr54pgx1jq2rwt0_bc9csyw0000gn/T/go-build576435461/b261/_x004.o:core-minimal.cpp:typeinfo for MyQAbstractListModel: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
/Users/arknable/Development/Stackninja/Tools/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/var/folders/85/kyr54pgx1jq2rwt0_bc9csyw0000gn/T/go-build576435461/b261/_x004.o:core-minimal.cpp:typeinfo for MyQChildEvent: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
/Users/arknable/Development/Stackninja/Tools/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/var/folders/85/kyr54pgx1jq2rwt0_bc9csyw0000gn/T/go-build576435461/b261/_x004.o:core-minimal.cpp:typeinfo for MyQCoreApplication: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
/Users/arknable/Development/Stackninja/Tools/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

this also happen when running `qtsetup android` on compiling example section. what do you think the problem is ? I'm assuming newest ndk is using `clang, right ?

Thanks

**Comment by therecipe** [comment]
Hey

Yeah, the problem is that both Qt and `therecipe/qt` will only work with clang atm, and Qt 5.11.2 on the other side will only work with gcc.

You will need to either update to Qt 5.12.x or downgrade `therecipe/qt` to https://github.com/therecipe/qt/commit/5251d3454c7c3600980c6791ebbbdee664b56156 and also use the android r14b NDK IIRC.

If this is not possible, then I will try to see if I can make `therecipe/qt` backward compatible to r14b `gcc` again.

**Comment by arknable** [comment]
@therecipe ah ok, so I think better to update to 5.12.

**Comment by arknable** [comment]
upgraded to Qt 5.12 works, I have fully setup now.
