### ISSUE TITLE
fatal error: 'QAbstractAnimation' file not found

### ISSUE THREAD

**Issue by oz-cdu** [therecipe/qt#284]
Hi, 
   Today, after upgrade golang to 1.81, then can't start

# github.com/therecipe/qt/core
../github.com/therecipe/qt/core/core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

**Comment by therecipe** [comment]
Hey

You probably need to re-run the setup: `$GOPATH/bin/qtsetup`

**Comment by oz-cdu** [comment]
It's work, thanks!
